### PR TITLE
Mapstore refactoring

### PR DESCRIPTION
**Pull request by sunye**
Now, MapDB and BerkeleyDB have a common code for Stores.

### CODE REVIEW

**Comment by gdaniel** [comment]
Can you pull the current version of master and integrate the changes I have made in DirectWrite[XX]Store? These changes are related to #54 #55, and #56 (mostly toArray and eObject methods).

**Comment by gdaniel** [comment]
@sunye nice work, I only have one concern on Store names: you simplified Store names in `map-core` module, which may be a good idea, but this naming convention is not followed in the sub-modules. For example `DirectWriteMapDBStore` extends `MapStore`, which may be confusing, especially because `MapStore` extends `AbstractDirectWriteStore`.

I would suggest to follow the existing convention and rename core-level stores `DirectWriteMapStore`, `DirectWriteMapListsStore` ...

@yvernageau what do you think?

Renaming all the existing DirectWrite stores (not only in Map) could be interesting, especially because all low-level stores use a direct write approach, but I think this can be done later on master.

**Comment by yvernageau** [comment]
Indeed, great work!

I'm pretty agree with the naming problem, and I'm agree with its solution too.
Because the `DirectWrite` stores are the real implementation of a `PersistentStore`, and that without them, there is no link between a resource and a backend, I think that the ideal would be to simplify the `DirectWrite` feature at the `core` level. But, the confusion would then be present there, because all stores don't extends the `DirectWrite` feature, they simply decorate them.
So I suggest adding the notion of `DirectWrite` in the class names, until we find a better idea.

However, I'm agree by the simplification of the name of `PersistenceBackend`s.

**Comment by sunye** [comment]
`MapDBDirectStore` and `BerkeleyDBDirectStore` are now empty classes and should be deleted. 

I didn't keep the prefix "DirectWrite" because as long as I understand, all stores directly write things. Moreover `AbstractPersistentStore` is an empty class and has only 1 concrete subclass, `AbstractDirectWriteStore`.  

I propose to remove all the "DirectWrite" prefixes and only use it if we indeed have stores with a different behavior.

**Comment by gdaniel** [comment]
@sunye There is a Read-only store in the HBase module. For now it extends `DirectWriteHBaseStore`, which is an issue, but I am not sure removing the prefix of other stores is interesting.

Anyway for now we need to be consistent. I propose to keep the `DirectWrite` prefix, merge the pull request with the updated names, and then decide what we should do about store names for all the backends (the PR here only concerns Map-based implementations).

**Pull request merged**
